[network]
    protocol = "websockets"
    host = "127.0.0.1"
    port = 8765

[data]
    data_folder = "/home/fslimani/declearn-bench/examples/mnist_quickrun/data_iid_n5"

[model]
    model_file = "/home/fslimani/declearn-bench/examples/mnist_quickrun/model_torch.py"

[optim]
    aggregator = "averaging"

    [optim.client_opt]
    lrate = 0.001
    modules = ["adam"]

    [optim.server_opt]
    lrate = 1.0

[run]
    rounds = 5

    [run.register]
    timeout = 15

    [run.training]
    batch_size = 48
    n_steps = 5

    [run.evaluate]
    batch_size = 128
    frequency = 999

[experiment]
    metrics = [["multi-classif", {labels = [0,1,2,3,4,5,6,7,8,9]}]]
